# Generated by Django 5.0.1 on 2024-02-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('availability', models.TextField(verbose_name='Наличие')),
                ('img_link', models.TextField(verbose_name='Ссылка на изображение')),
            ],
        ),
    ]
