# Generated by Django 5.0.1 on 2024-02-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Подробное описание преложения')),
            ],
            options={
                'verbose_name_plural': 'Книга пожеланий',
            },
        ),
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name_plural': 'Каталог книг'},
        ),
    ]
