# Generated by Django 5.0.1 on 2024-02-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_wishes_alter_catalog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='genre',
            field=models.TextField(default=1, verbose_name='Жанр'),
            preserve_default=False,
        ),
    ]
