# Generated by Django 5.0.1 on 2024-02-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_catalog_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='author',
            field=models.TextField(default=1, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
